version: 2.1
jobs:
  lint:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: install
          command: npm install
      - run:
          name: lint
          command: npm run lint
workflows:
  lint:
    jobs:
      - lint
