name: Deploy to preview
on:
  push:
    branches-ignore:
      - main
      - 'dependabot/**'
jobs:
  deploy_to_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Caching packages
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Install Dependencies
        run: npm install

      - name: Get hatena blog entries
        run: npm run hatena
        env:
          HATENA_NAME: ${{secrets.HATENA_NAME}}
          HATENA_PASS: ${{secrets.HATENA_PASS}}

      - name: Build with 11ty
        run: npm run build

      - name: Deploy to preview
        run: npx netlify deploy -d _site -a ${NETLIFY_AUTH_TOKEN} -s ${NETLIFY_SITE_ID}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
